module.exports = [
  { word: "Abrams", image: "https://files.catbox.moe/fdmu6m.png" },
  { word: "Bebop", image: "https://files.catbox.moe/aasbi0.png" },
  { word: "Billy", image: "https://files.catbox.moe/fpvr7p.png" },
  { word: "Calico", image: "https://files.catbox.moe/959w9o.png" },
  { word: "The Doorman", image: "https://files.catbox.moe/6ccb8y.png" },
  { word: "Drifter", image: "https://files.catbox.moe/euzelc.png" },
  { word: "Dynamo", image: "https://files.catbox.moe/4d6p6w.png" },
  { word: "Grey Talon", image: "https://files.catbox.moe/sb33hp.png" },
  { word: "Haze", image: "https://files.catbox.moe/jbfviw.png" },
  { word: "Holliday", image: "https://files.catbox.moe/7l2keg.png" },
  { word: "Infernus", image: "https://files.catbox.moe/5mx9r7.png" },
  { word: "Ivy", image: "https://files.catbox.moe/32vguj.png" },
  { word: "Kelvin", image: "https://files.catbox.moe/cg1oae.png" },
  { word: "Lady Geist", image: "https://files.catbox.moe/mjnoz8.png" },
  { word: "Lash", image: "https://files.catbox.moe/33qozg.png" },
  { word: "McGinnis", image: "https://files.catbox.moe/sgipzw.png" },
  { word: "Mina", image: "https://files.catbox.moe/uuo8o6.png" },
  { word: "Mirage", image: "https://files.catbox.moe/7sllye.png" },
  { word: "Mo & Krill", image: "https://files.catbox.moe/vpfwdy.png" },
  { word: "Paige", image: "https://files.catbox.moe/1r24xs.png" },
  { word: "Paradox", image: "https://files.catbox.moe/es8ft2.png" },
  { word: "Pocket", image: "https://files.catbox.moe/t30cvc.png" },
  { word: "Seven", image: "https://files.catbox.moe/upqlpj.png" },
  { word: "Shiv", image: "https://files.catbox.moe/i6edwu.png" },
  { word: "Sinclair", image: "https://files.catbox.moe/s07p9e.png" },
  { word: "Victor", image: "https://files.catbox.moe/4rur9l.png" },
  { word: "Vindicta", image: "https://files.catbox.moe/rzr9pi.png" },
  { word: "Viscous", image: "https://files.catbox.moe/g9n0np.png" },
  { word: "Vyper", image: "https://files.catbox.moe/t9nxbz.png" },
  { word: "Warden", image: "https://files.catbox.moe/zbdhle.png" },
  { word: "Wraith", image: "https://files.catbox.moe/e3dwbw.png" },
  { word: "Yamato", image: "https://files.catbox.moe/dcf100.png" },
];
